export const GENERAL_WORD_CHALLENGE_ITEMS = [
  { word: 'Adapt', hint: 'To adjust well to a new place, task, or situation.', difficulty: 'easy', category: 'Everyday vocabulary', source: 'General Vocabulary' },
  { word: 'Curious', hint: 'Eager to learn, ask questions, or discover something new.', difficulty: 'easy', category: 'Personality trait', source: 'General Vocabulary' },
  { word: 'Fragile', hint: 'Easy to break, damage, or harm.', difficulty: 'easy', category: 'Descriptive adjective', source: 'General Vocabulary' },
  { word: 'Observe', hint: 'To watch carefully and notice details.', difficulty: 'easy', category: 'Action verb', source: 'General Vocabulary' },
  { word: 'Combine', hint: 'To join two or more things into one.', difficulty: 'easy', category: 'Action verb', source: 'General Vocabulary' },
  { word: 'Predict', hint: 'To say what is likely to happen before it happens.', difficulty: 'medium', category: 'Thinking skill', source: 'General Vocabulary' },
  { word: 'Expand', hint: 'To become larger or make something larger.', difficulty: 'medium', category: 'Action verb', source: 'General Vocabulary' },
  { word: 'Precise', hint: 'Very exact, accurate, and carefully stated.', difficulty: 'medium', category: 'Descriptive adjective', source: 'General Vocabulary' },
  { word: 'Scarce', hint: 'Not easy to find because there is only a small amount.', difficulty: 'medium', category: 'Descriptive adjective', source: 'General Vocabulary' },
  { word: 'Vivid', hint: 'Very clear, bright, and easy to imagine.', difficulty: 'medium', category: 'Descriptive adjective', source: 'General Vocabulary' },
  { word: 'Resilient', hint: 'Able to recover quickly after difficulty or pressure.', difficulty: 'hard', category: 'Character trait', source: 'General Vocabulary' },
  { word: 'Innovate', hint: 'To introduce useful new ideas, methods, or products.', difficulty: 'hard', category: 'Action verb', source: 'General Vocabulary' },
  { word: 'Ambiguous', hint: 'Unclear because it can be understood in more than one way.', difficulty: 'hard', category: 'Descriptive adjective', source: 'General Vocabulary' },
  { word: 'Conserve', hint: 'To protect something from waste, loss, or damage.', difficulty: 'hard', category: 'Action verb', source: 'General Vocabulary' },
];

export const EXAM_WORD_CHALLENGE_ITEMS = [
  { word: 'Hypothesis', hint: 'A testable explanation proposed before gathering full evidence.', difficulty: 'easy', category: 'Science', source: 'Exam Terms' },
  { word: 'Equation', hint: 'A mathematical statement showing two expressions are equal.', difficulty: 'easy', category: 'Mathematics', source: 'Exam Terms' },
  { word: 'Ecosystem', hint: 'A community of living things interacting with their environment.', difficulty: 'easy', category: 'Biology', source: 'Exam Terms' },
  { word: 'Legislature', hint: 'The branch of government that makes laws.', difficulty: 'easy', category: 'Civics', source: 'Exam Terms' },
  { word: 'Molecule', hint: 'A group of atoms chemically bonded together.', difficulty: 'medium', category: 'Chemistry', source: 'Exam Terms' },
  { word: 'Velocity', hint: 'Speed measured together with direction.', difficulty: 'medium', category: 'Physics', source: 'Exam Terms' },
  { word: 'Thesis', hint: 'The main argument or central claim of an academic work.', difficulty: 'medium', category: 'Academic writing', source: 'Exam Terms' },
  { word: 'Algorithm', hint: 'A step-by-step process used to solve a problem or complete a task.', difficulty: 'medium', category: 'Computer science', source: 'Exam Terms' },
  { word: 'Mitosis', hint: 'The process in which one cell divides into two identical cells.', difficulty: 'hard', category: 'Biology', source: 'Exam Terms' },
  { word: 'Theorem', hint: 'A statement proven true using logical reasoning and established facts.', difficulty: 'hard', category: 'Mathematics', source: 'Exam Terms' },
  { word: 'Oxidation', hint: 'A chemical process involving the loss of electrons.', difficulty: 'hard', category: 'Chemistry', source: 'Exam Terms' },
  { word: 'Sovereignty', hint: 'The full authority of a state to govern itself.', difficulty: 'hard', category: 'Political science', source: 'Exam Terms' },
  { word: 'Photosynthesis', hint: 'The process plants use to make food from light, water, and carbon dioxide.', difficulty: 'medium', category: 'Biology', source: 'Exam Terms' },
  { word: 'Inference', hint: 'A conclusion reached using evidence and reasoning rather than direct statement.', difficulty: 'medium', category: 'Reading comprehension', source: 'Exam Terms' },
];

export const FUN_WORD_CHALLENGE_ITEMS = [
  { word: 'Otter', hint: 'A playful semi-aquatic animal known for floating on its back.', difficulty: 'easy', category: 'Animal', source: 'Fun Picks' },
  { word: 'Lantern', hint: 'A portable light often carried by hand.', difficulty: 'easy', category: 'Object', source: 'Fun Picks' },
  { word: 'Puzzle', hint: 'A game or problem that challenges you to find the answer.', difficulty: 'easy', category: 'Activity', source: 'Fun Picks' },
  { word: 'Dolphin', hint: 'An intelligent marine animal famous for clicking and leaping.', difficulty: 'easy', category: 'Animal', source: 'Fun Picks' },
  { word: 'Compass', hint: 'A tool that helps you find direction.', difficulty: 'medium', category: 'Object', source: 'Fun Picks' },
  { word: 'Cactus', hint: 'A plant that stores water and usually grows sharp spines.', difficulty: 'medium', category: 'Plant', source: 'Fun Picks' },
  { word: 'Volcano', hint: 'A mountain that can erupt with lava, ash, and gas.', difficulty: 'medium', category: 'Nature', source: 'Fun Picks' },
  { word: 'Rocket', hint: 'A vehicle designed to travel through space using thrust.', difficulty: 'medium', category: 'Technology', source: 'Fun Picks' },
  { word: 'Koala', hint: 'A tree-dwelling marsupial from Australia that eats eucalyptus leaves.', difficulty: 'hard', category: 'Animal', source: 'Fun Picks' },
  { word: 'Kaleidoscope', hint: 'A tube that creates changing colorful patterns with reflected light.', difficulty: 'hard', category: 'Object', source: 'Fun Picks' },
  { word: 'Firefly', hint: 'A small insect known for producing light at night.', difficulty: 'hard', category: 'Animal', source: 'Fun Picks' },
  { word: 'Treasure', hint: 'Something valuable or special that people search for or protect.', difficulty: 'easy', category: 'Object', source: 'Fun Picks' },
  { word: 'Parachute', hint: 'A device that slows a fall through the air.', difficulty: 'hard', category: 'Object', source: 'Fun Picks' },
  { word: 'Telescope', hint: 'An instrument used to view distant objects, especially in the sky.', difficulty: 'medium', category: 'Object', source: 'Fun Picks' },
];
